"""
ShadowMap PDF Report Generator
Generates professional intelligence reports in PDF format.
"""

from datetime import datetime
from typing import Dict, Any, Optional
from pathlib import Path
import io
from src.core.logging import get_logger
from src.pipeline.analyst import GraphAnalyst

logger = get_logger(__name__)


class ReportGenerator:
    """
    Generates PDF reports from the knowledge graph analysis.
    Uses markdown-to-PDF conversion for clean output.
    """
    
    def __init__(self):
        self.analyst = GraphAnalyst()
        self.output_dir = Path("reports")
        self.output_dir.mkdir(exist_ok=True)
    
    def generate_report(self, title: Optional[str] = None) -> Dict[str, Any]:
        """
        Generate a complete intelligence report.
        Returns the report content and file path.
        """
        # Get analysis from LLM Analyst
        analysis_result = self.analyst.generate_report()
        
        if analysis_result["status"] == "empty":
            return {
                "status": "empty",
                "message": "No data in graph to analyze"
            }
        
        if analysis_result["status"] == "error":
            return {
                "status": "error",
                "message": analysis_result.get("error", "Analysis failed")
            }
        
        # Build full report
        report_content = self._build_report(
            title=title or "Intelligence Report",
            analysis=analysis_result["report"],
            stats=analysis_result["stats"]
        )
        
        # Generate filename
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"shadowmap_report_{timestamp}"
        
        # Save as Markdown (can be converted to PDF by client)
        md_path = self.output_dir / f"{filename}.md"
        with open(md_path, "w", encoding="utf-8") as f:
            f.write(report_content)
        
        # Try to generate HTML version
        html_content = self._markdown_to_html(report_content)
        html_path = self.output_dir / f"{filename}.html"
        with open(html_path, "w", encoding="utf-8") as f:
            f.write(html_content)
        
        logger.info("report_generated", md_path=str(md_path), html_path=str(html_path))
        
        return {
            "status": "success",
            "markdown_path": str(md_path),
            "html_path": str(html_path),
            "content": report_content,
            "html_content": html_content,
            "stats": analysis_result["stats"]
        }
    
    def _build_report(self, title: str, analysis: str, stats: Dict) -> str:
        """Build the full report with header and metadata."""
        
        header = f"""# {title}

**Generated by ShadowMap Intelligence Platform**  
**Date:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}  
**Classification:** UNCLASSIFIED // FOR OFFICIAL USE ONLY

---

## Data Summary

| Metric | Value |
|--------|-------|
| Entities Analyzed | {stats.get('entity_count', 'N/A')} |
| Relationships Mapped | {stats.get('relationship_count', 'N/A')} |
| Analysis Engine | Gemini AI |
| Verification Status | Enabled |

---

"""
        
        footer = """

---

## Methodology

This report was generated using autonomous OSINT collection and AI-powered analysis:

1. **Discovery**: Automated search across public sources
2. **Extraction**: LLM-based entity and relationship extraction
3. **Verification**: Cross-referencing with Wikidata and sanctions databases
4. **Analysis**: AI-generated intelligence assessment

### Confidence Ratings

- **HIGH (0.8-1.0)**: Verified in multiple sources
- **MEDIUM (0.5-0.8)**: Single source, partially verified
- **LOW (0.0-0.5)**: Unverified or speculative

---

*This report is auto-generated. Human review recommended for operational decisions.*

**© ShadowMap Intelligence Platform**
"""
        
        return header + analysis + footer
    
    def _markdown_to_html(self, markdown_content: str) -> str:
        """Convert markdown to styled HTML for printing."""
        
        # Simple markdown to HTML conversion
        # In production, use a proper library like markdown2 or mistune
        html_body = markdown_content
        
        # Basic conversions
        import re
        
        # Headers
        html_body = re.sub(r'^# (.+)$', r'<h1>\1</h1>', html_body, flags=re.MULTILINE)
        html_body = re.sub(r'^## (.+)$', r'<h2>\1</h2>', html_body, flags=re.MULTILINE)
        html_body = re.sub(r'^### (.+)$', r'<h3>\1</h3>', html_body, flags=re.MULTILINE)
        
        # Bold
        html_body = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', html_body)
        
        # Italic
        html_body = re.sub(r'\*(.+?)\*', r'<em>\1</em>', html_body)
        
        # Line breaks
        html_body = html_body.replace('\n\n', '</p><p>')
        
        # Horizontal rules
        html_body = html_body.replace('---', '<hr>')
        
        # Tables (basic)
        html_body = re.sub(r'\|(.+)\|', r'<tr><td>\1</td></tr>', html_body)
        html_body = html_body.replace('|', '</td><td>')
        
        # Bullet points
        html_body = re.sub(r'^- (.+)$', r'<li>\1</li>', html_body, flags=re.MULTILINE)
        
        html_template = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ShadowMap Intelligence Report</title>
    <style>
        @media print {{
            body {{ font-size: 11pt; }}
            .no-print {{ display: none; }}
        }}
        
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            max-width: 800px;
            margin: 0 auto;
            padding: 40px;
            line-height: 1.6;
            color: #333;
        }}
        
        h1 {{
            color: #1a1a2e;
            border-bottom: 3px solid #e94560;
            padding-bottom: 10px;
        }}
        
        h2 {{
            color: #16213e;
            margin-top: 30px;
        }}
        
        h3 {{
            color: #0f3460;
        }}
        
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }}
        
        th, td {{
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }}
        
        th {{
            background-color: #1a1a2e;
            color: white;
        }}
        
        tr:nth-child(even) {{
            background-color: #f9f9f9;
        }}
        
        .risk-high {{
            color: #e94560;
            font-weight: bold;
        }}
        
        .risk-medium {{
            color: #f39c12;
        }}
        
        .risk-low {{
            color: #27ae60;
        }}
        
        hr {{
            border: none;
            border-top: 1px solid #ddd;
            margin: 30px 0;
        }}
        
        blockquote {{
            border-left: 4px solid #e94560;
            padding-left: 20px;
            margin-left: 0;
            color: #666;
        }}
        
        .header-meta {{
            color: #666;
            font-size: 0.9em;
        }}
        
        .footer {{
            margin-top: 50px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            font-size: 0.9em;
            color: #666;
        }}
        
        @page {{
            margin: 2cm;
        }}
    </style>
</head>
<body>
    <p>{html_body}</p>
    
    <div class="no-print" style="margin-top: 30px; text-align: center;">
        <button onclick="window.print()" style="padding: 10px 20px; font-size: 16px; cursor: pointer;">
            🖨️ Print / Save as PDF
        </button>
    </div>
</body>
</html>"""
        
        return html_template


# === API HELPER ===

def generate_pdf_report(title: Optional[str] = None) -> Dict[str, Any]:
    """
    Convenience function for API usage.
    """
    generator = ReportGenerator()
    return generator.generate_report(title=title)
